### ISSUE TITLE
Site is first showing content without css

### ISSUE THREAD

**Issue by asefcamel** [Tom-Bonnike/netlify-plugin-inline-critical-css#14]
Hi,

I'm using this plugin i a gridsome site. 
The plugin works fine but when i first enter the website it is showing content without css and after 2, 3 seconds i got the css styles back.

**Comment by Tom-Bonnike** [comment]
what’s the site so I can take a look please? also there’s a netlify bug messing up this plugin that still isn’t fixed AFAIK https://github.com/netlify/build/issues/1384

**Comment by asefcamel** [comment]
Hi thanks for the quick answer!! https://www.kyagency.be

**Comment by Tom-Bonnike** [comment]
I’m not sure but I think it’s because `critical` (which this package depends on) inlines the wrong critical CSS, it’s probably the JavaScript image loading that messes it up. It seems like it first has the styles for the fully loaded website:
![Screenshot 2020-09-17 at 18 00 40](https://user-images.githubusercontent.com/9154236/93496700-d5804380-f90f-11ea-8c18-14604463f9f6.png)

But because there’s no images the layout is messed up. Then only once the page has loaded, it loads the rest of the CSS (which I guess include the styles for the images loader), so it only shows up after that.

Either way, I can’t really help (as long as you don’t have Netlify’s bundle CSS post-processing enabled). You could try playing with options but I’m not sure it’s worth it. 🤷‍♂️ 

Closing, sorry.

**Comment by asefcamel** [comment]
Thankyou for looking at it, i hope i find a solution soon because this site is for a client 😫

**Comment by Tom-Bonnike** [comment]
Sorry that I can’t help more. Is inlining critical CSS really that… critical for you?

If it is, I think you could re-implement this yourself:
- Inline the styles for the site’s loader and make sure you don’t load the rest of the CSS
- On top of loading images (and whatever else), load the rest of the CSS using `https://github.com/filamentgroup/loadCSS`
